#!/bin/sh
#PrepaRPI_2

TERMINALTITLE="INSTALLATION DE TOUS LES MODULES"
##COULEURS##
RS="\033[1;31m" #rouge gras
NS="\033[0m" #normal
YS="\033[1;33m" #jaune gras
ys="\033[0;33m" #jaune
VS="\033[1;32m" #vert gras

#installation des pré-requis
apt-get clean
apt-get update
apt-get -y install git binutils make csh g++ sed gawk autoconf automake autotools-dev barrier libglib2.0-dev libnfc* libnfc-dev liblzma-dev libnfc-bin libusb-dev libtool gnome-terminal hexedit bless leafpad subversion gvfs-backends

##Mettre en FR##
echo $YS"choisir fr_FR.UTF-8 UTF-8
puis encore le même choix
Appuyez sur Entrée pour continuer."$NS
read "" 
clear
dpkg-reconfigure locales

cd ../
cd /root
#installation de Samba
choix=""
clear
until [ "$choix" = "o" ] || [ "$choix" = "n" ] ; do
echo $RS"Voulez-vous configurer Samba? (o/n)"$NS
read choix
clear
done
if [ "$choix" = "o" ] ; then
smbpasswd -a root
clear
echo "
[RPI4]
  comment=Commentaire dossier public
  path=/
  browseable=Yes
  writeable=Yes
  only guest=no
  create mask=0777
  directory mask=0777
  public=no
  read only=no
  force user=root" >> /etc/samba/smb.conf
systemctl enable smbd
service smbd restart
clear
echo "Pour ajouter le lecteur au réseau Windows:
Cliquez sur Connecter un Lecteur Réseau$NS
$VS\\[IP]\[RPI4]"
echo $RS"Appuyez sur Entrée pour continuer."$NS
read""
elif [ "$choix" = "n" ] ; then
clear
fi

#installation de BigDumper
choix=""
clear
until [ "$choix" = "o" ] || [ "$choix" = "n" ] ; do
echo $RS"Voulez-vous installer BigDumper? (o/n)"$NS
read choix
clear
done
if [ "$choix" = "o" ] ; then
git clone https://github.com/maxbrd/BigDumper.git
echo $RS"Merci de déplacer les 3 dossiers dans /root
puis appuyez sur Entrée."$NS
read ""
clear
chmod +x /root/BigDumper/bigdumperinstall
/root/BigDumper/bigdumperinstall
elif [ "$choix" = "n" ] ; then
clear
fi

#installation de CardPeek
choix=""
clear
until [ "$choix" = "o" ] || [ "$choix" = "n" ] ; do
echo $RS"Voulez-vous installer CardPeek? (o/n)"$NS
read choix
clear
done
if [ "$choix" = "o" ] ; then
apt-get install cardpeek
echo "[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=CardPeek
Comment=Tool to read the contents of smart card
Exec=cardpeek
Icon=cardpeek-logo
Path=
StartupNotify=false" >> /root/Desktop/CardPeek.desktop
clear
elif [ "$choix" = "n" ] ; then
clear
fi

#installation de TheLazyScript
choix=""
clear
until [ "$choix" = "o" ] || [ "$choix" = "n" ] ; do
echo $RS"Voulez-vous installer TheLazyScript? (o/n)"$NS
read choix
clear
done
if [ "$choix" = "o" ] ; then
git clone https://github.com/maxbrd/lscript.git
chmod +x /root/lscript/install.sh
cd /root/lscript
./install.sh
cd ../
elif [ "$choix" = "n" ] ; then
clear
fi


clear
echo $YS"TOUT EST INSTALLE."$NS